// Code generated by goagen v1.1.0-dirty, command line:
// $ goagen
// --design=github.com/tikasan/goa-oauth2-practice/design
// --out=$(GOPATH)/src/github.com/tikasan/goa-oauth2-practice
// --version=v1.1.0
//
// API "auth": Application Resource Href Factories
//
// The content of this file is auto-generated, DO NOT MODIFY

package app
