// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "auth": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/tikasan/goa-oauth2-practice/design
// --out=$(GOPATH)/src/github.com/tikasan/goa-oauth2-practice
// --version=v1.1.0

package app
