// Code generated by goagen v1.2.0-dirty, DO NOT EDIT.
//
// API "auth": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/tikasan/goa-oauth2-practice/design
// --out=$(GOPATH)/src/github.com/tikasan/goa-oauth2-practice
// --version=v1.1.0

package app

import (
	"github.com/goadesign/goa"
)

// GoaMessageJson media type (default view)
//
// Identifier: application/vnd.goa.message.json; view=default
type GoaMessageJSON struct {
	// message
	Message string `form:"message" json:"message" xml:"message"`
}

// Validate validates the GoaMessageJSON media type instance.
func (mt *GoaMessageJSON) Validate() (err error) {
	if mt.Message == "" {
		err = goa.MergeErrors(err, goa.MissingAttributeError(`response`, "message"))
	}
	return
}
